version: "3"
services:
  vendor-portal:
    image: godvindockerhub/selenium
    environment:
      - BROWSER
      - HOST=hub
      - XMLFILE=vendor-portal.xml
      - RUN=4
    volumes:
      - ./output.vendor-portal:/home/selenium-docker/test-output
  flight-reservation:
    image: godvindockerhub/selenium
    environment:
      - BROWSER
      - HOST=hub
      - XMLFILE=flight-reservation2.xml
      - RUN=4
    volumes:
      - ./output.flight-reservation:/home/selenium-docker/test-output